controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


login:
    path: /login
    controller: App\Controller\SecurityController::login

register:
    path: /register
    controller: App\Controller\RegistrationController::register


home:
    path: /home
    controller: App\Controller\HomeController::index
